#include "VGA.h"
#include <stdio.h>      /* printf, scanf, puts, NULL */
#include <stdlib.h>     /* srand, rand */
#include <time.h>  

#define LineAmount 6
#define ObstaculeAmount 4
#define XPositionAmount 3

int y =0;
int x=0;
int object=0;
int CarAnimation=0;
int Lives=3;
int Score=0;
int PersonAnimation=0;
int HeartAnimation=0;
int obstaculeToInstantIndex=1;
boolean Start=false;

unsigned char small_ball[] = { 
    RED, RED, RED, RED, RED, WHITE , 
    RED, RED, RED, RED, RED, WHITE , 
    RED, RED, RED, RED, RED, WHITE , 
    RED, RED, RED, RED, RED, WHITE , 
    RED, RED, RED, RED, RED, WHITE , 
    WHITE, WHITE, WHITE, WHITE, WHITE, WHITE,
};
struct Obstacule{
  int posX;
  int posY;
  int XPosiblePosition[XPositionAmount];
  int width ;
  int height;
  unsigned char *objectToInstantiate;
};
struct Line{
  int y1;
  int x1;
  int x2;
  int y2;
};
unsigned char Car[] = { 
    BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK,CYAN, CYAN, YELLOW, YELLOW, CYAN, RED, RED, RED, RED, CYAN, YELLOW, YELLOW, CYAN, CYAN, BLACK, BLACK, BLACK,
    BLACK, BLACK,BLACK, CYAN, BLUE, BLUE, BLUE, BLUE, RED, RED, RED, RED, BLUE, BLUE, BLUE, BLUE, CYAN, BLACK, BLACK, BLACK,
    BLACK, BLACK,BLACK, CYAN, BLUE, BLUE, BLUE, RED, RED, RED, RED, RED, RED, BLUE, BLUE, BLUE, CYAN, BLACK, BLACK, BLACK,
    BLACK, BLACK,BLACK, CYAN, CYAN, CYAN, CYAN, RED, RED, RED, RED, RED, RED, CYAN, CYAN, CYAN, CYAN, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, BLACK, RED, RED, RED, RED, RED, RED, BLACK, WHITE, WHITE, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, WHITE,PURPLE, PURPLE, BLACK, RED, RED, WHITE, WHITE, RED, RED, BLACK, PURPLE, PURPLE, WHITE, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, WHITE,PURPLE, PURPLE, BLACK, RED, RED, WHITE, WHITE, RED, RED, BLACK, PURPLE, PURPLE, WHITE, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, WHITE,PURPLE, PURPLE, BLACK, RED, RED, WHITE, WHITE, RED, RED, BLACK, PURPLE, PURPLE, WHITE, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, RED, RED, WHITE, WHITE, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, RED, RED, WHITE, WHITE, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, RED, RED, WHITE, WHITE, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, RED, RED, WHITE, WHITE, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, RED, RED, BLACK, BLACK, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK,BLACK,RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK, BLACK,  BLACK,
    BLACK, WHITE, WHITE, BLACK,RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, BLACK, WHITE, WHITE,   BLACK,
    WHITE, PURPLE, PURPLE,BLACK, RED, RED, RED, RED, RED, WHITE, WHITE, RED, RED, RED, RED, RED, BLACK, PURPLE, PURPLE, WHITE,//HERE
    WHITE, PURPLE, PURPLE, BLACK,RED, RED, RED, RED, RED, WHITE, WHITE, RED, RED, RED, RED, RED, BLACK, PURPLE, PURPLE,  WHITE,
    WHITE, PURPLE, PURPLE, BLACK,RED, RED, RED, RED, RED, WHITE, WHITE, RED, RED, RED, RED, RED, BLACK, PURPLE, PURPLE,  WHITE,
    WHITE, PURPLE, PURPLE, BLACK,RED, RED, RED, RED, RED, WHITE, WHITE, RED, RED, RED, RED, RED, BLACK, PURPLE, PURPLE,  WHITE,
    BLACK, BLACK, BLACK, BLACK,RED, RED, RED, RED, RED, WHITE, WHITE, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, //HERE 
    BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
    BLACK, BLACK, BLACK,BLACK, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, 
    
};

unsigned char TrafficLightGreen[] = { 
     WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, 
     WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED,RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW,YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN,GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
     WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE,  
     WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, 
    
};

unsigned char TrafficLightYellow[] = { 
     WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, 
     WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED,RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW,YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN,GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
     WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE,  
     WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, 
    
};
unsigned char TrafficLightRed[] = { 
     WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, 
     WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED,RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW,YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN,GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, 
     BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK,  
     BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
     WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE,  
     WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, 
    
};

unsigned char Car2[] = { 
    BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK,CYAN, CYAN, YELLOW, YELLOW, CYAN, BLUE, BLUE, BLUE, BLUE, CYAN, YELLOW, YELLOW, CYAN, CYAN, BLACK, BLACK, BLACK,
    BLACK, BLACK,BLACK, CYAN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, CYAN, BLACK, BLACK, BLACK,
    BLACK, BLACK,BLACK, CYAN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, CYAN, BLACK, BLACK, BLACK,
    BLACK, BLACK,BLACK, CYAN, CYAN, CYAN, CYAN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, CYAN, CYAN, CYAN, CYAN, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, WHITE, WHITE, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, WHITE,PURPLE, PURPLE, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, PURPLE, PURPLE, WHITE, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, WHITE,PURPLE, PURPLE, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, PURPLE, PURPLE, WHITE, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, WHITE,PURPLE, PURPLE, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, PURPLE, PURPLE, WHITE, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLUE, BLUE, BLACK, BLACK, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK,BLACK,BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK,  BLACK,
    BLACK, WHITE, WHITE, BLACK,BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLACK, WHITE, WHITE,   BLACK,
    WHITE, PURPLE, PURPLE,BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, PURPLE, PURPLE, WHITE,//HERE
    WHITE, PURPLE, PURPLE, BLACK,BLUE, BLUE, BLUE, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, PURPLE, PURPLE,  WHITE,
    WHITE, PURPLE, PURPLE, BLACK,BLUE, BLUE, BLUE, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, PURPLE, PURPLE,  WHITE,
    WHITE, PURPLE, PURPLE, BLACK,BLUE, BLUE, BLUE, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, PURPLE, PURPLE,  WHITE,
    BLACK, BLACK, BLACK, BLACK,BLUE, BLUE, BLUE, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, //HERE 
    BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
    BLACK, BLACK, BLACK,BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, 
    
};
unsigned char Car3[]={
    BLACK, BLACK, BLACK,BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, 
    BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
    BLACK, BLACK, BLACK, BLACK,BLUE, BLUE, BLUE, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, 
    WHITE, PURPLE, PURPLE, BLACK,BLUE, BLUE, BLUE, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, PURPLE, PURPLE,  WHITE,
    WHITE, PURPLE, PURPLE, BLACK,BLUE, BLUE, BLUE, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, PURPLE, PURPLE,  WHITE,
    WHITE, PURPLE, PURPLE, BLACK,BLUE, BLUE, BLUE, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, PURPLE, PURPLE,  WHITE,
    WHITE, PURPLE, PURPLE, BLACK,BLUE, BLUE, BLUE, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, PURPLE, PURPLE,  WHITE,
    BLACK, WHITE, WHITE, BLACK,BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLACK, WHITE, WHITE,   BLACK,
    BLACK, BLACK, BLACK,BLACK,BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLUE, BLUE, BLACK, BLACK, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, WHITE,PURPLE, PURPLE, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, PURPLE, PURPLE, WHITE, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, WHITE,PURPLE, PURPLE, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, PURPLE, PURPLE, WHITE, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, WHITE,PURPLE, PURPLE, BLACK, BLUE, BLUE, WHITE, WHITE, BLUE, BLUE, BLACK, PURPLE, PURPLE, WHITE, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, WHITE, WHITE, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,  BLACK,
    BLACK, BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK,BLACK, CYAN, CYAN, CYAN, CYAN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, CYAN, CYAN, CYAN, CYAN, BLACK, BLACK, BLACK,
    BLACK, BLACK,BLACK, CYAN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, CYAN, BLACK, BLACK, BLACK,
    BLACK, BLACK,BLACK, CYAN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, CYAN, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK,CYAN, CYAN, YELLOW, YELLOW, CYAN, BLUE, BLUE, BLUE, BLUE, CYAN, YELLOW, YELLOW, CYAN, CYAN, BLACK, BLACK, BLACK,
    BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK,BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, 
};

unsigned char Heart[]=
{
    GREEN,GREEN,BLACK,BLACK,GREEN,BLACK,BLACK,GREEN,GREEN,
    GREEN,BLACK,RED,RED,BLACK,RED,RED,BLACK,GREEN,
    BLACK,RED,RED,RED,RED,RED,RED,RED,BLACK,
    BLACK,RED,RED,RED,RED,RED,RED,RED,BLACK,
    GREEN,BLACK,RED,RED,RED,RED,RED,BLACK,GREEN,
    GREEN,GREEN,BLACK,RED,RED,RED,BLACK,GREEN,GREEN,
    GREEN,GREEN,GREEN,BLACK,RED,BLACK,GREEN,GREEN,GREEN,
    GREEN,GREEN,GREEN,GREEN,BLACK,GREEN,GREEN,GREEN,GREEN,
};

unsigned char Heart2[]=
{
    GREEN,GREEN,BLACK,BLACK,GREEN,BLACK,BLACK,GREEN,GREEN,
    GREEN,BLACK,PURPLE,PURPLE,BLACK,PURPLE,PURPLE,BLACK,GREEN,
    BLACK,PURPLE,PURPLE,PURPLE,PURPLE,PURPLE,PURPLE,PURPLE,BLACK,
    BLACK,PURPLE,PURPLE,PURPLE,PURPLE,PURPLE,PURPLE,PURPLE,BLACK,
    GREEN,BLACK,PURPLE,PURPLE,PURPLE,PURPLE,PURPLE,BLACK,GREEN,
    GREEN,GREEN,BLACK,PURPLE,PURPLE,PURPLE,BLACK,GREEN,GREEN,
    GREEN,GREEN,GREEN,BLACK,PURPLE,BLACK,GREEN,GREEN,GREEN,
    GREEN,GREEN,GREEN,GREEN,BLACK,GREEN,GREEN,GREEN,GREEN,
};

unsigned char Coin[]=
{
  GREEN,GREEN,GREEN,BLACK,BLACK,GREEN,GREEN,GREEN,
  GREEN,GREEN,BLACK,WHITE,WHITE,BLACK,GREEN,GREEN,
  GREEN,BLACK,WHITE,YELLOW,YELLOW,YELLOW,BLACK,GREEN,
  BLACK,YELLOW,WHITE,YELLOW,BLACK,YELLOW,YELLOW,BLACK,
  BLACK,YELLOW,WHITE,YELLOW,BLACK,YELLOW,YELLOW,BLACK,
  GREEN,BLACK,WHITE,YELLOW,YELLOW,YELLOW,BLACK,GREEN,
  GREEN,GREEN,BLACK,WHITE,WHITE,BLACK,GREEN,GREEN,
  GREEN,GREEN,GREEN,BLACK,BLACK,GREEN,GREEN,GREEN,
  
};

unsigned char Bricks[] = {
  RED,RED,RED,RED,RED,RED,BLACK,RED,RED,RED,RED,RED,BLACK,RED,RED,RED,RED,
  RED,RED,RED,RED,RED,RED,BLACK,RED,RED,RED,RED,RED,BLACK,RED,RED,RED,RED,
  BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
  RED,RED,RED,RED,BLACK,RED,RED,RED,RED,RED,BLACK,RED,RED,RED,RED,RED,RED,
  RED,RED,RED,RED,BLACK,RED,RED,RED,RED,RED,BLACK,RED,RED,RED,RED,RED,RED,
  BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
  RED,RED,BLACK,RED,RED,RED,RED,RED,BLACK,RED,RED,RED,RED,RED,BLACK,RED,RED,
  RED,RED,BLACK,RED,RED,RED,RED,RED,BLACK,RED,RED,RED,RED,RED,BLACK,RED,RED, 
};

unsigned char Person[] = {
    GREEN, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN,GREEN,
    GREEN, GREEN, YELLOW, YELLOW, WHITE, WHITE, YELLOW, YELLOW, GREEN, GREEN,   
    GREEN, GREEN, YELLOW, WHITE, WHITE, CYAN, WHITE, GREEN, GREEN,GREEN,
    GREEN, GREEN, YELLOW, WHITE, WHITE, WHITE, WHITE, GREEN, GREEN,GREEN,    
    GREEN, GREEN, YELLOW, WHITE, WHITE, WHITE, GREEN, GREEN, GREEN,GREEN,    
    GREEN, GREEN, BLUE, WHITE, WHITE, WHITE, BLUE, GREEN, GREEN,GREEN,   
    GREEN, BLUE, BLUE, BLUE, WHITE, BLUE, BLUE, BLUE, GREEN,GREEN,   
    GREEN, WHITE, BLUE, BLUE, BLACK, BLUE, BLUE, WHITE, GREEN,GREEN,
    GREEN, WHITE, BLUE, BLUE, BLACK, BLUE, BLUE, WHITE, GREEN,GREEN,   
    GREEN, WHITE, BLUE, BLUE, WHITE, BLUE, BLUE, WHITE, GREEN,GREEN,
    GREEN, GREEN, CYAN, CYAN, CYAN, CYAN, CYAN, GREEN, GREEN,GREEN,
    GREEN, GREEN, CYAN, CYAN, CYAN, CYAN, CYAN, GREEN, GREEN,GREEN,
    GREEN, GREEN, CYAN, CYAN, CYAN, CYAN, CYAN, GREEN, GREEN,GREEN,
    GREEN, GREEN, GREEN, WHITE, GREEN, WHITE, GREEN, GREEN, GREEN,GREEN,
    GREEN, GREEN, GREEN, WHITE, GREEN, GREEN, WHITE, GREEN, GREEN,GREEN,
    GREEN, GREEN, GREEN, WHITE, GREEN, GREEN, GREEN, WHITE, GREEN,GREEN,
    GREEN, GREEN, RED, RED, GREEN, RED, RED, GREEN, GREEN,GREEN,  

};

unsigned char Person2[] = {
    GREEN,GREEN, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN,GREEN,
    GREEN,GREEN, GREEN, YELLOW, YELLOW, WHITE, WHITE, YELLOW, YELLOW, GREEN,GREEN,
    GREEN,GREEN, GREEN, YELLOW, WHITE, WHITE, CYAN, WHITE, GREEN, GREEN,GREEN,
    GREEN,GREEN, GREEN, YELLOW, WHITE, WHITE, WHITE, WHITE, GREEN, GREEN,GREEN,
    GREEN,GREEN, GREEN, YELLOW, WHITE, WHITE, WHITE, GREEN, GREEN, GREEN,GREEN,    
    GREEN,GREEN, GREEN, BLUE, WHITE, WHITE, WHITE, BLUE, GREEN, GREEN,GREEN,
    GREEN,GREEN, BLUE, BLUE, BLUE, WHITE, BLUE, BLUE, BLUE, GREEN,GREEN,   
    GREEN,GREEN, WHITE, BLUE, BLUE, BLACK, BLUE, BLUE, WHITE, GREEN,GREEN,
    GREEN,WHITE, GREEN, BLUE, BLUE, BLACK, BLUE, BLUE, GREEN, WHITE,GREEN,   
    WHITE,GREEN, GREEN, BLUE, BLUE, WHITE, BLUE, BLUE, GREEN, GREEN,WHITE,
    GREEN,GREEN, GREEN, CYAN, CYAN, CYAN, CYAN, CYAN, GREEN, GREEN,GREEN,
    GREEN,GREEN, GREEN, CYAN, CYAN, CYAN, CYAN, CYAN, GREEN, GREEN,GREEN,
    GREEN,GREEN, GREEN, CYAN, CYAN, CYAN, CYAN, CYAN, GREEN, GREEN,GREEN,
    GREEN,GREEN, GREEN, GREEN, WHITE, GREEN, WHITE, GREEN, GREEN, GREEN,GREEN,
    GREEN,GREEN, GREEN, GREEN, WHITE, GREEN, WHITE, GREEN, GREEN, GREEN,GREEN,
    GREEN,GREEN, GREEN, GREEN, WHITE, GREEN, WHITE, GREEN, GREEN, GREEN,GREEN,
    GREEN,GREEN, GREEN, RED, RED, GREEN, RED, RED, GREEN, GREEN,GREEN,    

};

unsigned char Title[]={
   BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,
   WHITE,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,WHITE,
   WHITE,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,
   WHITE,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,
   WHITE,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,
   WHITE,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,
   WHITE,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,
   WHITE,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,WHITE,
   BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,
};

unsigned char Cone[] = {
   RED,BLACK,RED,BLACK,RED,
   WHITE,WHITE,WHITE,WHITE,WHITE,
   BLACK,WHITE,WHITE,WHITE,BLACK,
   WHITE,WHITE,WHITE,WHITE,WHITE,
};
unsigned char Trap[] = { 
    BLACK,WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK, WHITE, BLACK,
    WHITE,WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE,
};

 struct Line lines[LineAmount];
 struct Obstacule Obstacules[ObstaculeAmount];
 void InitializePositionsObstacules(int x1,int x2,int x3, unsigned char* objectToInstant,int width , int height, int index){
   Obstacules[index].posY=0;
   Obstacules[index].XPosiblePosition[0]=x1;
   Obstacules[index].XPosiblePosition[1]=x2;
   Obstacules[index].XPosiblePosition[2]=x3;
   Obstacules[index].posX= Obstacules[index].XPosiblePosition[rand()%XPositionAmount];
   Obstacules[index].objectToInstantiate=objectToInstant;
     Obstacules[index].width = width;
     Obstacules[index].height= height;
 }
  
  
 void InitializeObstacules()
 {
     InitializePositionsObstacules(40,83,115,Car3,20,29,0);
   InitializePositionsObstacules(50,83,118,Bricks,17,8,1);
   InitializePositionsObstacules(55,90,123,Cone,5,4,2);
   InitializePositionsObstacules(50,90,123,Trap,19,2,3);
 }
void setup(){
   srand(0);
  VGA.begin(VGAWISHBONESLOT(9),CHARMAPWISHBONESLOT(10));
  
  
  VGA.clear();
  VGA.setBackgroundColor(BLACK);
  VGA.setColor(RED);
  //VGA.printtext(0,0,"Death Race");
  VGA.writeArea(0,0, 9, 9, Title);
  delay(500);
  VGA.printtext(25,10,"Color Bar Test");
  int  i,x1 =73, x2=107,y1=0, y2=0;
   for(i = 0 ; i<LineAmount;i++)
   {
      lines[i].x1 = x1;
       lines[i].y1= y1;
      lines[i].x2 =x2;
     lines[i].y2 = y2;
     y1=y2+=20;
        
   }
   InitializeObstacules();
  //DrawLimits();

  //Loading();
  
}

void Loading(){
  
  /*for(int i = 0; i < 100; i++){
    if(i%2==0){
      VGA.putPixel(i, 71, GREEN);
      VGA.putPixel(i, 70, GREEN);
    }else{ 
      VGA.putPixel(i, 71, CYAN);
      VGA.putPixel(i, 70, CYAN);
    }
    delay(50);
  
  }*/
  char* buffer;
  
  for(int i = 0; i < 100; i++){
    //itoa(i, buffer, 10);
    if(i%2==0){
      VGA.putPixel(i, 75, WHITE);
      VGA.putPixel(i, 74, WHITE);
    }else{ 
      VGA.putPixel(i, 75, CYAN);
      VGA.putPixel(i, 74, CYAN);
    }

    VGA.printtext(i+5, 72, buffer);
    delay(1000);
  }
}

void DrawLimits(){
  for(int i =0 ; i<120; i++){
    if(i%4==0){
      //LEFT
      VGA.putPixel(41, i, WHITE);
      VGA.putPixel(42, i, WHITE);

      //RIGHT
      VGA.putPixel(141, i, WHITE);
      VGA.putPixel(142, i, WHITE);

    }
    //LEFT
    VGA.putPixel(40, i, WHITE);
    VGA.putPixel(43, i, WHITE);
    //RIGHT
    VGA.putPixel(140, i, WHITE);
    VGA.putPixel(143, i, WHITE);
  }
}

void DrawObject(){
    
      VGA.clear();
      
       
      
       // VGA.writeArea(105, 70-(i*8), 20, 29, Car2);
      
      
      VGA.setColor( GREEN );
      
        VGA.drawRect( 0, 10, 40, 118 );
        VGA.drawRect( 144, 0, 15, 119 );
        VGA.setBackgroundColor(CYAN);
        VGA.setColor( BLACK );
       
       
       
       
        VGA.setColor( RED );
        char* buffers="";
        itoa(Score,buffers,10);
        VGA.printtext(0,0,"Score");
        VGA.writeArea(0, 11, 8, 8, Coin);
        VGA.printtext(9,11,buffers,true );
        
        DrawPerson();
        DrawLines();
        DrawLimits();
        DrawLives();
        if(!Start){
          TrafficLightAnimation(); 
          Start=true;
        }
        DrawObstacules();
        DrawCar();
        
        Score++;
     
    //TESTING DIMENSIONS
    VGA.putPixel(0,0,GREEN);
    VGA.putPixel(0,119,RED);
    VGA.putPixel(158,0,GREEN);
    VGA.putPixel(158,119,GREEN);

}

void TrafficLightAnimation()
{
    VGA.setColor( WHITE );
    VGA.drawRect( 44, 12, 97, 35 );
    VGA.writeArea(83, 15, 16, 30, TrafficLightRed);
    delay(800);
    VGA.writeArea(83, 15, 16, 30, TrafficLightYellow);
    delay(800);
    VGA.writeArea(83, 15, 16, 30, TrafficLightGreen);
    delay(800);
    VGA.drawRect( 44, 12, 97, 35 );
    VGA.setColor( BLACK );
    VGA.setBackgroundColor(WHITE);
    VGA.printtext(83,25,"GO");
    delay(500);
}

void DrawPerson()
{
  if(PersonAnimation==0)
    VGA.writeArea(15, 90, 10, 17, Person);
  else
    VGA.writeArea(15, 90, 11, 17, Person2);
  PersonAnimation++;
  
  if(PersonAnimation>1)
    PersonAnimation=0;
}

void DrawCar()
{
    if(CarAnimation==0)
      VGA.writeArea(83, 85, 20, 29, Car);
    else
      VGA.writeArea(83, 86, 20, 29, Car);
    
    CarAnimation++;
    if(CarAnimation>1)
      CarAnimation=0;
}

void DrawLine(int posX, int posY)
{
   VGA.setColor( WHITE );
   VGA.drawRect( posX, posY, 4, 6 );
}

void DrawLives()
{
  int pos =6;
  for(int i=0;i<Lives;i++)
  {
    if(HeartAnimation==0)
      VGA.writeArea(pos,110 , 9, 8, Heart);
    else
      VGA.writeArea(pos,110 , 9, 8, Heart2);
    pos+=10;
  }
}

void DrawObstacules()
{
     //obstaculeToInstantIndex = rand() % ObstaculeAmount;   
    if(Obstacules[obstaculeToInstantIndex].posY>95)
    {
      
      obstaculeToInstantIndex = rand() % ObstaculeAmount;
       Obstacules[obstaculeToInstantIndex].posX= Obstacules[obstaculeToInstantIndex].XPosiblePosition[rand()%XPositionAmount];  
       Obstacules[obstaculeToInstantIndex].posY=0;
    }
    
    VGA.writeArea(Obstacules[obstaculeToInstantIndex].posX, Obstacules[obstaculeToInstantIndex].posY, Obstacules[obstaculeToInstantIndex].width, Obstacules[obstaculeToInstantIndex].height, Obstacules[obstaculeToInstantIndex].objectToInstantiate); 
    Obstacules[obstaculeToInstantIndex].posY +=3;

    
}

void DrawLines()
{
  
   int i ;
   
   for(i = 0;i<LineAmount;i++)
   {
     DrawLine(lines[i].x1, lines[i].y1) ;
     DrawLine(lines[i].x2, lines[i].y2) ;
     if( lines[i].y1>110)
       lines[i].y1=0;
     if( lines[i].y2>110)
       lines[i].y2=0;
     lines[i].y1+=10;
     lines[i].y2+=10;
   }
}
  
void loop(){
  DrawObject();
  delay(500);
}
